###recuperar todas las peliculas
GET http://localhost:1234/movies

###recuperar una pelicula por ID
GET http://localhost:1234/movies/5ad1a235-0d9c-410a-b32b-220d91689a08

###recuperar todas las peliculas por un genero
GET http://localhost:1234/movies?genre=ACTIOn

###POST -  CREAR UNA PELICULA
POST http://localhost:1234/movies
Content-Type: application/json

{
  "sql": "select * from users",
  "title": "Error",
  "year": 1996,
  "director": "SAMUDEV",
  "duration": 10,
  "poster": "https://i.ebayimg.com/images/g/QFQAAOSwAQpfjaA6/s-l1200.jpg",
  "genre": ["Action", "Sci-Fi"]
}

### Eliminar una pelicula por ID
DELETE http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3


###Actualizar unos datos de una pelicula
PATCH http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
Content-Type: application/json

{
  "id": "abc",
  "title": "Holi!!!",
  "year": 2025
}



